# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff08c98f9d46be6c7bbe8e29c9bc1d035d4842500e4df334c57765e2bbc90506f0aae52cf306d7302b5358d39da9da8ecf5d2dd6bb5860ad6b2a81e0d85a081e

test:
  secret_key_base: 332048a512270ee777301498133034fe3688cf4a584c4b0b9c92d2ecc9ea08caf335abf8391a9a6a540c378697170afb02925baa4c70f907f8acf2bbe665afe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
